---
- name: Stop agent service
  systemd:
    name: agent
    state: stopped
    enabled: true

- name: Remove config & package directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/opt/stackable-work/parcels/"
    - "/opt/stackable-work/config/"
    - "/tmp/zookeeper"
    - "/tmp/kafka-logs"

- name: Start agent service
  systemd:
    name: agent
    state: started
    enabled: true

- name: Ensure Kafka port is gone
  wait_for:
    port: 9092
    state: absent
    delay: 10

- name: Ensure Zookeeper client port is gone
  wait_for:
    port: 2181
    state: absent
    delay: 10

- name: Ensure Zookeeper leader election port is gone
  wait_for:
    port: 3888
    state: absent
    delay: 10

- name: Ensure Zookeeper comms port is gone
  wait_for:
    port: 2888
    state: absent
    delay: 10
